#!/bin/sh

copy_iso() {
  iso=$1
  disk=/dev/$2
  rdisk=/dev/r$2
  hdiutil convert -format UDRW -o $iso $iso
  mv $iso.dmg $iso.img
  diskutil unmountDisk $disk
  sudo dd if=$iso.img of=$rdisk bs=1m
  diskutil eject $disk
}

iso2img() {
  hdiutil convert -format UDRW -o ~/Desktop/$1.img ~/Downloads/$1
}

joins() {
  local IFS="$1"
  shift
  echo "$*"
}

md2odt() {
  pandoc $1.md --latex-engine=xelatex -o $1.odt
}
