#!/bin/sh

lesson_new() {
  curriculum_dir="$PROJECTS/curriculum"
  mkdir "$curriculum_dir/$1/$2"
  touch "$curriculum_dir/$1/$2/$2.md"

read -d '' lesson_yml << EOF
---
title: "$2"
type: "$1"  # challenge, exercise, article, tutorial, video
description: "Lesson Description."
tags: "tag-one, tag-two"
ignore:
- "$2.md"

EOF

  echo "$lesson_yml" > "$curriculum_dir/$1/$2/.lesson.yml"
}
