#!/bin/sh

react_new() {
  project=$1

  mkdir -p $project/{app,public}
  mkdir -p $project/app/{components,config,containers,utils}
  touch $project/app/index.js
  touch $project/README.md
  cd $project

  npm init --force
  npm install axios react react-dom --save
  npm install webpack html-webpack-plugin webpack-dev-server --save-dev
  npm install babel-{core,loader} babel-preset-react --save-dev

  webpack_config_js
  babelrc
  index_html

  gitignore
  git init
  git add .
  git commit -m "initial"
}

babelrc() {
  read -d '' contents << EOF
{
  "presets": [
    "react"
  ]
}
EOF

  echo $contents > .babelrc
}

gitignore() {
  read -d '' contents << EOF
.env
node_modules
EOF

  echo $contents > .gitignore
}

webpack_config_js() {
  read -d '' contents << EOF
var HtmlWebpackPlugin = require('html-webpack-plugin')
var HtmlWebpackPluginConfig = new HtmlWebpackPlugin({
  template: __dirname + '/app/index.html',
  filename: 'index.html',
  inject: 'body'
});

module.exports = {
  entry: [
  './app/index.js'
  ],
  module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader' }
    ]
  },
  output: {
    filename: 'index_bundle.js',
    path: __dirname + '/public'
  },
  plugins: [HtmlWebpackPluginConfig]
}
EOF

  echo $contents > webpack.config.js
}

index_html() {
  read -d '' contents << EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>React.js</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div id="app"></div>
</body>
</html>
EOF

  echo $contents > ./app/index.html
}

: '
Before running this bash function, you need npm and webpack installed

```
$ brew install node
$ npm install webpack -g
```

Typical structure of a React.js App

```
/app
  - components
  - containers
  - config
  - utils
  index.js
  index.html
/dist
  index.html
  index_bundle.js
package.json
webpack.config.js
.gitignore
```

'
