#!/bin/sh

temperature() {
  url="http://forecast.weather.gov/MapClick.php?lat=$LATITUDE&lon=$LONGITUDE&FcstType=dwml"
  xml=$(curl -s $url)
  temperature=$(echo $xml | xmllint --xpath 'string(/dwml/data[2]/parameters/temperature[1]/value)' -)
  echo "The current temperature is... $temperature degrees F." | cowsay -f tux
}
