#!/bin/bash

blog() {
  open "https://$GITHUB_USERNAME.github.io/"
}

gists() {
  open "https://gist.github.com/$GITHUB_USERNAME"
}

gmail() {
  open https://gmail.com/
}

keep() {
  open http://keep.google.com/
}

github() {
  open "http://github.com/$GITHUB_USERNAME/repositories"
}

twitter() {
  open "https://twitter.com/$TWITTER_USERNAME"
}
