#!/bin/sh

blog() {
  open "https://$GITHUB_USERNAME.github.io/"
}

mygists() {
  open "https://gist.github.com/$GITHUB_USERNAME"
}

gmail() {
  open https://gmail.com/
}

horizon() {
  if [ $# -eq 0 ]; then
    folder=${PWD##*/}
    open "https://learn.launchacademy.com/lessons/$folder"
  else
    open "https://learn.launchacademy.com/lessons/$1"
  fi
}

keep() {
  open http://keep.google.com/
}

github() {
  open "http://github.com/$GITHUB_USERNAME/repositories"
}

questions() {
  open https://learn.launchacademy.com/questions?query=unanswered
}

twitter() {
  open "https://twitter.com/$TWITTER_USERNAME"
}
