#!/bin/bash

webapp_new() {
  location=$*

read -d '' index_html << EOF
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Webapp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- http://ionicabizau.github.io/gridly/example/ -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/gridly/1.4.8/gridly.min.css" rel="stylesheet" />
    <link href="style.css" rel="stylesheet">
  </head>

  <body>
    <div class="row">
      <div class="col">
        <h1>Primary Heading</h1>
        <p>Only one per page, please.</p>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <h2>Communicating with Web Servers</h2>
        <p>
          The Internet consists of <em>millions</em> of web servers, each one
          waiting for you to make a request for the resources they provide. They
          offer information such as the current weather conditions, stock market
          prices, and even
          <a href="https://api.nasa.gov/api.html#apod">images from other worlds</a>.
          The best part is, <strong>all of these servers speak HTTP</strong>.
        <p>
      </div>

      <div class="col">
        <h2>Todo</h2>
        <ul>
          <li>This is a list item</li>
          <li>So is this - there could be more</li>
          <li>Make sure to style list items to:
            <ul>
              <li>Not forgetting child list items</li>
              <li>Not forgetting child list items</li>
              <li>Not forgetting child list items</li>
              <li>Not forgetting child list items</li>
            </ul>
          </li>
          <li>A couple more</li>
          <li>top level list items</li>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <h2>Code</h2>
        <div class="code">
          # weather.rb
          require "net/http"
          require "active_support/core_ext/hash"
          require "pp"

          weather_url = "http://forecast.weather.gov/MapClick.php?lat=42.35&lon=-71.06&FcstType=dwml"
          uri = URI.parse(weather_url)            # convert the URL string to a URI object
          response = Net::HTTP.get_response(uri)  # issue a HTTP GET request
          body = Hash.from_xml(response.body)     # convert XML to a more familiar data type

          pp body  # "pretty-print" the hash
        </div>
      </div>
    </div>

    <script src="main.js" defer></script>
  </body>
</html>

EOF

read -d '' style_css << EOF
@import url(https://fonts.googleapis.com/css?family=Open+Sans|Libre+Baskerville|Share+Tech+Mono);

h1, h2, h3, h4, h5, h6 {
  font-family: "Open Sans", Georgia, Cambria, "Times New Roman", Times, serif;
  color: #274156;
}

body {
  font-family:  "Libre Baskerville", "Helvetica Neue", Helvetica, Arial, sans-serif;
  color: #605856;
  background-color: #FBFCFF;
  margin: 0 10%;
}

div {
  border-radius: 10px;
  font-size: 24px;
}

.code {
  font-family: "Share Tech Mono", Consolas, "Liberation Mono", Courier, monospace;
  background-color: #D0CCD0;
  white-space: pre;
}

#flash {
  background-color: #E0F0F1;
  font-size: 32px;
  margin: 1ex 0;
  padding: 1ex 0;
  text-align: center;
}

EOF

  echo "$index_html" > "$location/index.html"
  echo "$style_css" > "$location/style.css"
  echo "" > "$location/main.js"
}
